# Generated by Django 5.0.6 on 2024-05-12 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="create",
            new_name="created",
        ),
    ]
